FROM sdwebui_base:rtx4090

ENV SDWEBUI_PORT=${SDWEBUI_PORT}
ENV JUPYTER_PORT=${JUPYTER_PORT}

# 复制启动脚本到容器中
COPY /context/scripts/*.sh /scripts/
RUN chmod +x /scripts/*.sh

# 启动
ENTRYPOINT /scripts/run_jupyter.sh & /scripts/run_python.sh