FROM auto_undercoat:rtx4090

ENV AUTO_UNDERCOAT_PORT=${AUTO_UNDERCOAT_PORT}

# 复制启动脚本到容器中
COPY /context/scripts/*.sh /scripts/
RUN chmod +x /scripts/*.sh

# 启动
ENTRYPOINT /scripts/run_auto_undercoat.sh
# && /scripts/run_jupyter.sh
