FROM comfyui_ext:rtx4090

ENV COMFYUI_PORT=${COMFYUI_PORT}

# 复制启动脚本到容器中
COPY /context/scripts/*.sh /scripts/
RUN chmod +x /scripts/*.sh

# 快速启动方式
COPY /context/scripts/*.sh /
RUN cp /run_comfyui.sh /cui.sh
RUN chmod +x /*.sh

# 启动
# ENTRYPOINT /scripts/run_comfyui.sh