# 定义锚点
defaults: &defaults
  dockerfilesDir: ./dockerfile
  contextDir: ./context

templateVariables:
  # 基础路径
  host_base: /mnt/flies/AI_research/Stable_Diffusion
  # 宿主中的Stable Diffusion WebUI文件夹路径
  host_sdw: ${host_base}/stable-diffusion-webui-master
  # 容器中的Stable Diffusion WebUI文件夹路径
  cont_sdw: /home/stable-diffusion-webui
  # 宿主中的 ComfyUI 文件夹路径
  host_cui: ${host_base}/ComfyUI
  # 容器中的 ComfyUI 文件夹路径
  cont_cui: /home/ComfyUI
  # 容器中的 TPSMM 文件夹路径
  cont_stk: /home/StableTalker

# 引用锚点
dockerBuildConfig:
  conda_build:
    <<: *defaults
    tag: conda:jupyter
    dockerfile: Dockerfile.conda
    label: CONDA_IMAGE.LABEL
    hint: CONDA_IMAGE.HINT

  py_build:
    <<: *defaults
    tag: py:3.10.6-torch2.0.0
    dockerfile: Dockerfile.pytorch
    label: PYTORCH_IMAGE.LABEL
    hint: PYTORCH_IMAGE.HINT
    dependencies: [conda_build]

  sdwebui_base_build:
    <<: *defaults
    tag: sdwebui_base:rtx4090
    dockerfile: Dockerfile.sdwebui_base
    label: SDWEBUI_BASE_IMAGE.LABEL
    dependencies: [conda_build, py_build]

  sdwebui_ext_build:
    <<: *defaults
    tag: sdwebui_ext:rtx4090
    dockerfile: Dockerfile.sdwebui_ext
    label: SDWEBUI_EXT_IMAGE.LABEL
    hint: SDWEBUI_EXT_IMAGE.HINT
    dependencies: [conda_build, py_build, sdwebui_base_build]
    endpointBuild: true
    serviceOptions:
      serviceName: sd_service
      containerName: sd_container
      launchDockerfile: Dockerfile.sdwebui_ext.launch
      portMappings:
        JUPYTER_PORT: 33333
        SDWEBUI_PORT: 7860
      launch:
        test: false
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache
        - ${host_sdw}/models:${cont_sdw}/models
        - ${host_sdw}/embeddings:${cont_sdw}/embeddings
        - ${host_sdw}/interrogate:${cont_sdw}/interrogate
        - ${host_sdw}/models/SadTalker/checkpoints:${cont_sdw}/extensions/SadTalker/checkpoints/
        - ${host_sdw}/models/SadTalker/gfpgan:${cont_sdw}/extensions/SadTalker/gfpgan/
        - ${host_sdw}/outputs:${cont_sdw}/outputs
        - ${host_sdw}/extensions/sd-webui-controlnet/models:${cont_sdw}/extensions/sd-webui-controlnet/models
        - ${host_sdw}/extensions/sd-webui-controlnet/annotator/downloads:${cont_sdw}/extensions/sd-webui-controlnet/annotator/downloads
        - ${host_sdw}/cache.json:${cont_sdw}/cache.json
        - ${host_sdw}/config.json:${cont_sdw}/config.json
        - /home/lco/GitHub/OneClick-stable-diffusion/configs/wildcards_lib:${cont_sdw}/extensions/stable-diffusion-webui-wildcards/wildcards

  lama_cleaner_build:
    <<: *defaults
    tag: lama_cleaner:rtx4090
    dockerfile: Dockerfile.lama_cleaner
    label: LAMA_CLEANER_IMAGE.LABEL
    hint: LAMA_CLEANER_IMAGE.HINT
    dependencies: [conda_build, py_build]
    endpointBuild: true
    serviceOptions:
      serviceName: lama_cleaner
      containerName: lama_cleaner_container
      launchDockerfile: Dockerfile.lama_cleaner.launch
      portMappings:
        LAMA_CLEANER_PORT: 8080
      launch:
        test: false
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache

  comfyui_base_build:
    <<: *defaults
    tag: comfyui_base:rtx4090
    dockerfile: Dockerfile.comfyui_base
    label: COMFYUI_BASE_IMAGE.LABEL
    hint: COMFYUI_BASE_IMAGE.HINT
    dependencies: [conda_build, py_build]

  comfyui_ext_build:
    <<: *defaults
    tag: comfyui_ext:rtx4090
    dockerfile: Dockerfile.comfyui_ext
    label: COMFYUI_EXT_IMAGE.LABEL
    hint: COMFYUI_EXT_IMAGE.HINT
    dependencies: [conda_build, py_build, comfyui_base_build]
    endpointBuild: true
    serviceOptions:
      serviceName: comfyui
      containerName: comfyui_container
      launchDockerfile: Dockerfile.comfyui.launch
      portMappings:
        COMFYUI_PORT: 8188
      launch:
        test: false
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache
        - ${host_sdw}/models/Stable-diffusion:${cont_cui}/models/checkpoints
        - ${host_sdw}/extensions/sd-webui-controlnet/models:${cont_cui}/models/controlnet
        - ${host_sdw}/models/Lora:${cont_cui}/models/loras
        - ${host_cui}/models:${cont_cui}/models
        - ${host_cui}/custom_nodes/comfy_controlnet_preprocessors/ckpts:${cont_cui}/custom_nodes/comfy_controlnet_preprocessors/ckpts

  stable_talker_build:
    <<: *defaults
    tag: stable_talker:rtx4090
    dockerfile: Dockerfile.stable_talker
    label: STABLE_TALKER_IMAGE.LABEL
    hint: STABLE_TALKER_IMAGE.HINT
    dependencies: [conda_build, py_build]
    endpointBuild: true
    serviceOptions:
      serviceName: st
      containerName: st_container
      launchDockerfile: Dockerfile.stable_talker.launch
      portMappings: []
      launch:
        test: true
        prod: false
      mountVolumes:
        - /home/lco/GitHub/StableTalker:${cont_stk}
        - /home/lco/下载/tps_docker_demo:${cont_stk}/input
        - /home/lco/下载/output:${cont_stk}/output
        - /mnt/flies/AI_research/Thin-Plate-Spline-Motion-Model/checkpoints:${cont_stk}/models
        # - /mnt/flies/AI_research/Thin-Plate-Spline-Motion-Model/shape_predictor_68_face_landmarks.dat:${cont_stk}/shape_predictor_68_face_landmarks.dat

        # - /home/lco/GitHub/OneClick-stable-diffusion/python/tpsmm/predict.py:${cont_stk}/predict.py
        # - /home/lco/GitHub/OneClick-stable-diffusion/python/tpsmm/predictor.py:${cont_stk}/predictor.py
