dockerfilesDir: ./dockerfile
contextDir: ./context

baseBuildConfig:
  conda_build:
    tag: conda:jupyter
    dockerfile: Dockerfile.conda
    label: CONDA_IMAGE.LABEL
    hint: CONDA_IMAGE.HINT

  py_build:
    tag: py:3.10.6-torch2.0.0
    dockerfile: Dockerfile.pytorch
    label: PYTORCH_IMAGE.LABEL
    hint: PYTORCH_IMAGE.HINT
    dependencies: [conda_build]

  sdwebui_base_build:
    tag: sdwebui_base:rtx4090
    launchDockerfile: Dockerfile.sdwebui_base.launch
    dockerfile: Dockerfile.sdwebui_base
    label: SDWEBUI_BASE_IMAGE.LABEL
    dependencies: [conda_build, py_build]

  sdwebui_ext_build:
    tag: sdwebui_ext:rtx4090
    launchDockerfile: Dockerfile.sdwebui_ext.launch
    dockerfile: Dockerfile.sdwebui_ext
    label: SDWEBUI_EXT_IMAGE.LABEL
    hint: SDWEBUI_EXT_IMAGE.HINT
    dependencies: [conda_build, py_build, sdwebui_base_build]

  lama_cleaner_build:
    tag: lama_cleaner:rtx4090
    launchDockerfile: Dockerfile.lama_cleaner.launch
    dockerfile: Dockerfile.lama_cleaner
    label: LAMA_CLEANER_IMAGE.LABEL
    hint: LAMA_CLEANER_IMAGE.HINT
    dependencies: [conda_build, py_build]

targetBuilds: [sdwebui_ext_build,lama_cleaner_build]