# 定义锚点
defaults: &defaults
  dockerfilesDir: ./dockerfile
  contextDir: ./context

templateVariables:
  # 基础路径
  host_base: /mnt/flies/AI_research/Stable_Diffusion
  # 宿主中的Stable Diffusion WebUI文件夹路径
  host_sdw: ${host_base}/stable-diffusion-webui-master
  # 容器中的Stable Diffusion WebUI文件夹路径
  cont_sdw: /home/stable-diffusion-webui
  # 宿主中的 ComfyUI 文件夹路径
  host_cui: ${host_base}/ComfyUI
  # 容器中的 ComfyUI 文件夹路径
  cont_cui: /home/ComfyUI
  # 宿主中的 StableTalker 文件夹路径
  host_stk: ${host_base}/StableTalker
  # 容器中的 StableTalker 文件夹路径
  cont_stk: /home/StableTalker
  # 宿主中的 Whisper-WebUI 文件夹路径
  host_ww: ${host_base}/Whisper-WebUI
  # 容器中的 Whisper-WebUI 文件夹路径
  cont_ww: /home/Whisper-WebUI
  # 宿主中的 Faster-Whisper-WebUI 文件夹路径
  host_fww: ${host_base}/faster-whisper-webui
  # 容器中的 Faster-Whisper-WebUI 文件夹路径
  cont_fww: /home/faster-whisper-webui

# 引用锚点
dockerBuildConfig:
  conda_build:
    <<: *defaults
    tag: conda:jupyter
    dockerfile: Dockerfile.conda
    label: CONDA_IMAGE.LABEL
    hint: CONDA_IMAGE.HINT

  py_build:
    <<: *defaults
    tag: py:3.10.6-torch2.0.0
    dockerfile: Dockerfile.pytorch
    label: PYTORCH_IMAGE.LABEL
    hint: PYTORCH_IMAGE.HINT
    dependencies: [conda_build]

  sdwebui_base_build:
    <<: *defaults
    tag: sdwebui_base:rtx4090
    dockerfile: Dockerfile.sdwebui_base
    label: SDWEBUI_BASE_IMAGE.LABEL
    dependencies: [conda_build, py_build]

  sdwebui_ext_build:
    <<: *defaults
    tag: sdwebui_ext:rtx4090
    dockerfile: Dockerfile.sdwebui_ext
    label: SDWEBUI_EXT_IMAGE.LABEL
    hint: SDWEBUI_EXT_IMAGE.HINT
    dependencies: [conda_build, py_build, sdwebui_base_build]
    endpointBuild: true
    serviceOptions:
      serviceName: sd_service
      containerName: sd_container
      launchDockerfile: Dockerfile.sdwebui_ext.launch
      portMappings:
        JUPYTER_PORT: 33333
        SDWEBUI_PORT: 7860
      launch:
        test: true
        prod: true
      mountVolumes:
        - ${host_base}/.cache:/root/.cache:rw
        - ${host_sdw}/models:${cont_sdw}/models:rw
        - ${host_sdw}/embeddings:${cont_sdw}/embeddings:rw
        - ${host_sdw}/interrogate:${cont_sdw}/interrogate:ro
        - ${host_sdw}/models/SadTalker/checkpoints:${cont_sdw}/extensions/SadTalker/checkpoints/:ro
        - ${host_sdw}/models/SadTalker/gfpgan:${cont_sdw}/extensions/SadTalker/gfpgan/:ro
        - ${host_sdw}/outputs:${cont_sdw}/outputs:rw
        - ${host_sdw}/extensions/sd-webui-controlnet/models:${cont_sdw}/extensions/sd-webui-controlnet/models:rw
        - ${host_sdw}/extensions/sd-webui-controlnet/annotator/downloads:${cont_sdw}/extensions/sd-webui-controlnet/annotator/downloads:rw
        - ${host_sdw}/extensions/sd-webui-segment-anything/models/grounding-dino/groundingdino_swinb_cogcoor.pth:${cont_sdw}/extensions/sd-webui-segment-anything/models/grounding-dino/groundingdino_swinb_cogcoor.pth
        - ${host_sdw}/extensions/sd-webui-segment-anything/models/grounding-dino/groundingdino_swint_ogc.pth:${cont_sdw}/extensions/sd-webui-segment-anything/models/grounding-dino/groundingdino_swint_ogc.pth
        - ${host_sdw}/cache.json:${cont_sdw}/cache.json:rw
        - ${host_sdw}/config.json:${cont_sdw}/config.json:rw
        - ${host_sdw}/ui-config:${cont_sdw}/ui-config:rw
        - /home/lco/GitHub/OneClick-stable-diffusion/configs/wildcards_lib:${cont_sdw}/extensions/stable-diffusion-webui-wildcards/wildcards:ro

  lama_cleaner_build:
    <<: *defaults
    tag: lama_cleaner:rtx4090
    dockerfile: Dockerfile.lama_cleaner
    label: LAMA_CLEANER_IMAGE.LABEL
    hint: LAMA_CLEANER_IMAGE.HINT
    dependencies: [conda_build, py_build]
    endpointBuild: true
    serviceOptions:
      serviceName: lama_cleaner
      containerName: lama_cleaner_container
      launchDockerfile: Dockerfile.lama_cleaner.launch
      portMappings:
        LAMA_CLEANER_PORT: 8080
      launch:
        test: true
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache

  comfyui_base_build:
    <<: *defaults
    tag: comfyui_base:rtx4090
    dockerfile: Dockerfile.comfyui_base
    label: COMFYUI_BASE_IMAGE.LABEL
    hint: COMFYUI_BASE_IMAGE.HINT
    dependencies: [conda_build, py_build]

  comfyui_ext_build:
    <<: *defaults
    tag: comfyui_ext:rtx4090
    dockerfile: Dockerfile.comfyui_ext
    label: COMFYUI_EXT_IMAGE.LABEL
    hint: COMFYUI_EXT_IMAGE.HINT
    dependencies: [conda_build, py_build, comfyui_base_build]
    endpointBuild: true
    serviceOptions:
      serviceName: comfyui
      containerName: comfyui_container
      launchDockerfile: Dockerfile.comfyui.launch
      portMappings:
        COMFYUI_PORT: 8188
      launch:
        test: false
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache
        - ${host_sdw}/models/Stable-diffusion:${cont_cui}/models/checkpoints
        - ${host_sdw}/extensions/sd-webui-controlnet/models:${cont_cui}/models/controlnet
        - ${host_sdw}/models/Lora:${cont_cui}/models/loras
        - ${host_sdw}/models/VAE:${cont_cui}/models/vae
        - ${host_cui}/models:${cont_cui}/models
        - ${host_cui}/custom_nodes/comfy_controlnet_preprocessors/ckpts:${cont_cui}/custom_nodes/comfy_controlnet_preprocessors/ckpts

  stable_talker_build:
    <<: *defaults
    tag: stable_talker:rtx4090
    dockerfile: Dockerfile.stable_talker
    label: STABLE_TALKER_IMAGE.LABEL
    hint: STABLE_TALKER_IMAGE.HINT
    dependencies: [conda_build, py_build]
    endpointBuild: true
    serviceOptions:
      serviceName: st
      containerName: st_container
      launchDockerfile: Dockerfile.stable_talker.launch
      portMappings:
        STABLE_TALKER_PORT: 7868
      launch:
        test: true
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache
        - /home/lco/GitHub/StableTalker:${cont_stk}
        - ${host_stk}/output:${cont_stk}/output
        - ${host_stk}/models:${cont_stk}/models
        - ~/.ssh:/root/.ssh-localhost:ro
        # - ${host_stk}/submodules/GFPGAN/gfpgan/weights:${cont_stk}/submodules/GFPGAN/gfpgan/weights
        # - /mnt/flies/AI_research/Thin-Plate-Spline-Motion-Model/shape_predictor_68_face_landmarks.dat:${cont_stk}/shape_predictor_68_face_landmarks.dat

        # - /home/lco/GitHub/OneClick-stable-diffusion/python/tpsmm/predict.py:${cont_stk}/predict.py
        # - /home/lco/GitHub/OneClick-stable-diffusion/python/tpsmm/predictor.py:${cont_stk}/predictor.py

  whisper_webui_build:
    <<: *defaults
    tag: whisper_webui:rtx4090
    dockerfile: Dockerfile.whisper_webui
    label: WHISPER_WEBUI_IMAGE.LABEL
    hint: WHISPER_WEBUI_IMAGE.HINT
    dependencies: [conda_build, py_build]
    endpointBuild: true
    serviceOptions:
      serviceName: ww
      containerName: ww_container
      launchDockerfile: Dockerfile.whisper_webui.launch
      portMappings:
        WHISPER_WEBUI_PORT: 9000
        FASTER_WHISPER_WEBUI_PORT: 9001
      launch:
        test: true
        prod: false
      mountVolumes:
        - ${host_base}/.cache:/root/.cache
        - ${host_ww}:${cont_ww}
        - ${host_ww}/models:${cont_ww}/models
        - ${host_fww}/models/faster-whisper:${cont_fww}/models/faster-whisper