version: '3.8'
services:
  sd:
    build:
          context: .
          dockerfile: Dockerfile
          args:
            app_env: sdwebui
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "33333:33333"
      - "7860:7860"
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    stdin_open: true
    tty: true 