FROM sdwebui_base:rtx4090

ENV SDWEBUI_PORT=${SDWEBUI_PORT}
ENV JUPYTER_PORT=${JUPYTER_PORT}

# 复制启动脚本到容器中
COPY /scripts/*.sh /scripts/
RUN chmod +x /scripts/*.sh

# 启动startup脚本
ENTRYPOINT /scripts/startup.sh