FROM py:3.10.6-torch2.0.0

ENV NOTEBOOK_DIR /home

WORKDIR $NOTEBOOK_DIR

# 设置默认 shell 为 bash，并使用“-i”选项启动shell
SHELL ["/bin/bash", "-c", "-i"];

RUN git clone https://huggingface.co/spaces/Anonymous-sub/Rerender

RUN cd Rerender && \
    conda activate py3.10.6 && \
    pip install -r requirements.txt && \
    cd /; 