FROM sdwebui_ext:rtx4090

WORKDIR $NOTEBOOK_DIR

RUN git clone --depth=1 https://github.com/Sanster/lama-cleaner
RUN cd lama-cleaner && \
    conda activate py3.10.6 && \
    python -m pip install -e . 
RUN conda activate py3.10.6 && python -m pip install \
    realesrgan \
    gfpgan \
    rembg